---
- iosxr_config:
    lines: 
      - hostname {{ hostname }}
      - domain name {{ domain_name }}
  vars:
    ansible_user: admin
    ansible_ssh_pass: admin
    ansible_port: 8022
    ansible_network_os: iosxr
    ansible_host_key_checking: false
